nickjj/flask-static-digest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,30 +1,75 @@
-name: CI
+name: "CI"
 
 on:
-  push:
-    branches:
-      - main
   pull_request:
     branches:
-      - main
+      - "*"
+  push:
+    branches:
+      - "main"
+      - "master"
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fasT: false
-      matrix:
-        distro: [ubuntu1804, ubuntu2004, debian9, debian10]
+  test:
+    runs-on: "ubuntu-22.04"
 
     steps:
-    - name: Set up Docker
-      uses: docker/setup-buildx-action@v2
+      - uses: "actions/checkout@v2"
 
-    - name: Download test shim
-      run: wget -O ${{ github.workspace }}/tests/test.sh https://gist.githubusercontent.com/nickjj/d12353b5b601e33cd62fda111359957a/raw
+      - name: "Set up Python 3.8"
+        uses: "actions/setup-python@v1"
+        with:
+          python-version: "3.8"
 
-    - name: Make test shim executable
-      run: chmod +x ${{ github.workspace }}/tests/test.sh
+      - name: "Install dependencies"
+        run: |
+          pip3 install flake8 Flask==1.1.2
+          pip3 install -e .
 
-    - name: Run tests
-      run: ${{ github.workspace }}/tests/test.sh
+      - name: "Lint code base"
+        run: |
+          flake8 .
+
+      - name: "Run test suite"
+        run: |
+          cd tests/example_app
+          export FLASK_APP=example.app
+
+          ls -laR example/static/ | wc -l \
+          | grep -q "26" \
+          && (echo "File count before compiling test: pass" && exit 0) \
+          || (echo "File count before compiling test: fail" && exit 1)
+
+          flask digest compile \
+          && ls -laR example/static/ | wc -l \
+          | grep -q "36" \
+          && (echo "File count after compiling test: pass" && exit 0) \
+          || (echo "File count after compiling test: fail" && exit 1)
+
+          grep -q "js/modules/hello.js" example/static/cache_manifest.json \
+          && (echo "Cache manifest has nested file test: pass" && exit 0) \
+          || (echo "Cache manifest has nested file test: fail" && exit 1)
+
+          grep -q "js/modules/hello-d41d8cd98f00b204e9800998ecf8427e.js" example/static/cache_manifest.json \
+          && (echo "Cache manifest has digested file test: pass" && exit 0) \
+          || (echo "Cache manifest has digested file test: fail" && exit 1)
+
+          flask run &
+          sleep 5 \
+          && curl http://localhost:5000 \
+          | grep -q 'https://cdn.example.com/static/css/app-d41d8cd98f00b204e9800998ecf8427e.css' \
+          && (echo 'Stylesheet is md5 tagged test: pass' && exit 0) \
+          || (echo 'Stylesheet is md5 tagged test: fail' && exit 1)
+
+          flask digest clean \
+          && ls -laR example/static/ | wc -l \
+          | grep -q "26" \
+          && (echo "File count after cleaning test: pass" && exit 0) \
+          || (echo "File count after cleaning test: fail" && exit 1)
+
+          flask run -p 5001 &
+          sleep 5 \
+          && curl http://localhost:5001 \
+          | grep -q 'https://cdn.example.com/static/js/app.js' \
+          && (echo 'Javascript is not md5 tagged test: pass' && exit 0) \
+          || (echo 'Javascript is not md5 tagged test: fail' && exit 1)
