nickjj/flask-static-digest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,31 +1,89 @@
 name: CI
-
-on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
-
+on: [push]
 jobs:
   build:
     runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        distro: [ubuntu1804, ubuntu2004, debian9, debian10]
-
     steps:
-    - uses: "actions/checkout@v2"
-    - name: Set up Docker
-      uses: docker/setup-buildx-action@v2
-
-    - name: Download test shim
-      run: wget -O ${{ github.workspace }}/tests/test.sh https://gist.githubusercontent.com/nickjj/d12353b5b601e33cd62fda111359957a/raw
-
-    - name: Make test shim executable
-      run: chmod +x ${{ github.workspace }}/tests/test.sh
-
-    - name: Run tests
-      run: ${{ github.workspace }}/tests/test.sh
+      - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+      - name: Install dependencies
+        run: |
+          pip install flake8 Flask==1.1.1
+          pip install -e .
+          flake8 .
+      - name: Change directory and set environment variable
+        run: |
+          cd tests/example_app
+          echo "FLASK_APP=example.app" >> $GITHUB_ENV
+      - name: File count before compiling test
+        run: |
+          ls -laR example/static/ | wc -l | grep -q "26"
+          if [ $? -eq 0 ]; then
+            echo "File count before compiling test: pass"
+          else
+            echo "File count before compiling test: fail"
+            exit 1
+          fi
+      - name: Digest compile and file count check
+        run: |
+          flask digest compile
+          ls -laR example/static/ | wc -l | grep -q "36"
+          if [ $? -eq 0 ]; then
+            echo "File count after compiling test: pass"
+          else
+            echo "File count after compiling test: fail"
+            exit 1
+          fi
+      - name: Cache manifest has nested file test
+        run: |
+          grep -q "js/modules/hello.js" example/static/cache_manifest.json
+          if [ $? -eq 0 ]; then
+            echo "Cache manifest has nested file test: pass"
+          else
+            echo "Cache manifest has nested file test: fail"
+            exit 1
+          fi
+      - name: Cache manifest has digested file test
+        run: |
+          grep -q "js/modules/hello-d41d8cd98f00b204e9800998ecf8427e.js" example/static/cache_manifest.json
+          if [ $? -eq 0 ]; then
+            echo "Cache manifest has digested file test: pass"
+          else
+            echo "Cache manifest has digested file test: fail"
+            exit 1
+          fi
+      - name: Stylesheet is md5 tagged test
+        run: |
+          flask run &
+          sleep 5
+          curl http://localhost:5000 | grep -q 'https://cdn.example.com/static/css/app-d41d8cd98f00b204e9800998ecf8427e.css'
+          if [ $? -eq 0 ]; then
+            echo 'Stylesheet is md5 tagged test: pass'
+          else
+            echo 'Stylesheet is md5 tagged test: fail'
+            exit 1
+          fi
+      - name: Digest clean and file count check
+        run: |
+          flask digest clean
+          ls -laR example/static/ | wc -l | grep -q "26"
+          if [ $? -eq 0 ]; then
+            echo "File count after cleaning test: pass"
+          else
+            echo "File count after cleaning test: fail"
+            exit 1
+          fi
+      - name: Javascript is not md5 tagged test
+        run: |
+          flask run -p 5001 &
+          sleep 5
+          curl http://localhost:5001 | grep -q 'https://cdn.example.com/static/js/app.js'
+          if [ $? -eq 0 ]; then
+            echo 'Javascript is not md5 tagged test: pass'
+          else
+            echo 'Javascript is not md5 tagged test: fail'
+            exit 1
+          fi
