toblerity/shapely

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,175 +1,67 @@
-name: Tests (Linux)
+name: Python package
 
-on: [push, pull_request]
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
-  test:
-    name: Python ${{ matrix.python }} (GEOS ${{ matrix.geos }}, speedups ${{ matrix.speedups }}, numpy ${{ matrix.numpy || 'not installed' }})
-    # runs-on: ubuntu-latest
-    runs-on: ubuntu-22.04
+  build:
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
+        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
+        geos-version: ["3.5.2", "3.6.4", "3.7.3", "3.8.1", "3.9.0beta2", "master"]
+        speedups: [1, 0]
+        numpy: [1, 0]
         include:
-          # 2015
-          - python: 3.5
-            geos: 3.5.2
-            numpy: 1.10.4
+          - python-version: "3.9-dev"
+            geos-version: "master"
             speedups: 1
-          - python: 3.5
-            geos: 3.5.2
-            numpy: 1.10.4
-            speedups: 0
-          - python: 3.5
-            geos: 3.5.2
-            speedups: 0
-          # 2017
-          - python: 3.6
-            geos: 3.6.4
-            numpy: 1.13.3
-            speeedups: 1
-          - python: 3.6
-            geos: 3.6.4
-            numpy: 1.13.3
-            speeedups: 0
-          - python: 3.6
-            geos: 3.6.4
-            speeedups: 0
-          # 2018
-          - python: 3.7
-            geos: 3.7.3
-            numpy: 1.15.4
-            speedups: 1
-          - python: 3.7
-            geos: 3.7.3
-            numpy: 1.15.4
-            speedups: 0
-          - python: 3.7
-            geos: 3.7.3
-            speedups: 0
-          # 2019
-          - python: 3.8
-            geos: 3.8.1
-            numpy: 1.17.5
-            speedups: 1
-          - python: 3.8
-            geos: 3.8.1
-            numpy: 1.17.5
-            speedups: 0
-          - python: 3.8
-            geos: 3.8.1
-            speedups: 0
-          # 2020
-          - python: 3.9
-            geos: 3.9.0
-            numpy: 1.19.5
-            speedups: 1
-          - python: 3.9
-            geos: 3.9.0
-            numpy: 1.19.5
-            speedups: 0
-          - python: 3.9
-            geos: 3.9.0
-            speedups: 0
-          # dev
-          - python: 3.9
-            geos: master
-            speedups: 1
-
-    env:
-      GEOS_VERSION: ${{ matrix.geos }}
-      GEOS_INSTALL: ${{ github.workspace }}/geosinstall/geos-${{ matrix.geos }}
-      SPEEDUPS: ${{ matrix.speedups }}
-
+            numpy: 1
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python }}
-
-      - name: Cache GEOS and pip packages
-        uses: actions/cache@v4
-        with:
-          key: ${{ runner.os }}-geos-${{ matrix.geos }}
-          path: |
-            ~/.cache/pip
-            ${{ github.workspace }}/geosinstall
-
-      - name: Install GEOS
-        shell: bash
-        run: |
-          chmod +x ./ci/install_geos.sh
-          ./ci/install_geos.sh
-          cd ${{ github.workspace }}
-
-      - name: Install python dependencies
-        shell: bash
-        run: |
-          pip install --disable-pip-version-check --upgrade pip
-          pip install --upgrade wheel
-          if [ "$GEOS_VERSION" = "master" ]; then
-            pip install --upgrade --pre Cython numpy;
-          elif [ "$SPEEDUPS" == "1" ]; then
-            pip install --install-option="--no-cython-compile" cython;
-            pip install --upgrade numpy==${{ matrix.numpy }};
-          elif [ -n "${{ matrix.numpy }}" ]; then
-            pip install --upgrade numpy==${{ matrix.numpy }};
-          else
-            pip uninstall --yes numpy;
-          fi
-          pip install --upgrade coveralls pytest-cov pytest
-          pip list
-
-      - name: Set environment variables
-        shell: bash
-        run: |
-          echo "LD_LIBRARY_PATH=$GEOS_INSTALL/lib" >> $GITHUB_ENV
-          echo $GEOS_INSTALL/bin >> $GITHUB_PATH
-
-      - name: Build and install Shapely
-        shell: bash
-        run: |
-          pip install -v -e .
-
-      - name: Overview of the Python environment (pip list)
-        shell: bash
-        run: |
-          pip list
-
-      - name: Run tests
-        shell: bash
-        continue-on-error: ${{ matrix.geos == 'master' }}
-        run: |
-          if [ "$SPEEDUPS" == "1" ]; then SPEEDUPS_FLAG=--with-speedups; else SPEEDUPS_FLAG=--without-speedups; fi
-          python -c "from shapely import geos; print(geos.geos_version_string)"
-          python -c "from shapely import speedups; print(speedups.enabled)"
-          python -m pytest --cov shapely --cov-report term-missing "${SPEEDUPS_FLAG}"
-
-      - name: Run doctests
-        if: ${{ matrix.python == '3.8' && matrix.numpy && matrix.speedups == '1' }}
-        shell: bash
-        run: |
-          python -m pytest shapely --doctest-modules
-
-      - name: Upload coverage
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          COVERALLS_PARALLEL: true
-        shell: bash
-        run: |
-          coveralls --service=github || echo "!! intermittent coveralls failure"
-
-  coveralls:
-    name: Indicate completion to coveralls.io
-    needs: test
-    runs-on: ubuntu-latest
-    container: python:3-slim
-    steps:
-    - name: Finished
+    - uses: actions/checkout@v2
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Cache pip
+      uses: actions/cache@v4
+      with:
+        path: ~/.cache/pip
+        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-pip-
+    - name: Cache GEOS
+      uses: actions/cache@v4
+      with:
+        path: ${{ github.workspace }}/geosinstall
+        key: ${{ runner.os }}-geos-${{ matrix.geos-version }}
+    - name: Install dependencies
       run: |
-        pip3 install --upgrade coveralls
-        coveralls --finish || echo "!! intermittent coveralls failure"
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        export GEOS_INSTALL=${{ github.workspace }}/geosinstall/geos-${{ matrix.geos-version }}
+        ./ci/install_geos.sh
+        pip install --disable-pip-version-check --upgrade pip
+        pip install --upgrade wheel
+        if [ "${{ matrix.speedups }}" == "1" ]; then pip install --install-option="--no-cython-compile" cython; fi
+        if [ "${{ matrix.numpy }}" == "0" ]; then pip uninstall --yes numpy; fi
+        if [ "${{ matrix.speedups }}" == "1" ]; then SPEEDUPS_FLAG=--with-speedups; else SPEEDUPS_FLAG=--without-speedups; fi
+        pip install --upgrade coveralls pytest-cov pytest>=3.8
+    - name: Install package
+      run: |
+        export GEOS_CONFIG=${{ github.workspace }}/geosinstall/geos-${{ matrix.geos-version }}/bin/geos-config
+        pip install -v -e .[all]
+    - name: Run tests
+      run: |
+        export LD_LIBRARY_PATH=${{ github.workspace }}/geosinstall/geos-${{ matrix.geos-version }}/lib
+        export DYLD_LIBRARY_PATH=${{ github.workspace }}/geosinstall/geos-${{ matrix.geos-version }}/lib
+        python -c "from shapely.geos import geos_version; print(geos_version)"
+        python -m pytest --cov shapely --cov-report term-missing "${SPEEDUPS_FLAG}"
+        if [[ "${{ matrix.python-version }}" == "3.8" && "${{ matrix.numpy }}" == "1" && "${{ matrix.speedups }}" == "1" ]]; then python -m pytest shapely --doctest-modules; fi
+    - name: Coveralls
+      if: success()
+      run: coveralls || echo "!! intermittent coveralls failure"
